module Sections
    class Register_Forgot < SitePrism::Section

        #Elementos do registro
        element :register_first_name, '#customer\.firstName'
        element :register_last_name, '#customer\.lastName'
        element :register_address, '#customer\.address\.street'
        element :register_city, '#customer\.address\.city'
        element :register_state, '#customer\.address\.state'
        element :register_zip_code, '#customer\.address\.zipCode'
        element :register_phone, '#customer\.phoneNumber'
        element :register_ssn, '#customer\.ssn'
        element :register_username, '#customer\.username'
        element :register_password, '#customer\.password'
        element :register_confirm_password, '#repeatedPassword'
        element :register_form_button, 'input[value="Register"]'
        element :register_first_name_error, '#customer\.firstName\.errors'
        element :register_last_name_error, '#customer\.lastName\.errors'
        element :register_address_error, '#customer\.address\.street\.errors'
        element :register_city_error, '#customer\.address\.city\.errors'
        element :register_state_error, '#customer\.address\.state\.errors'
        element :register_zip_code_error, '#customer\.address\.zipCode\.errors'
        element :register_phone_error, '#customer\.phoneNumber\.errors'
        element :register_ssn_error, '#customer\.ssn\.errors'
        element :register_username_error, '#customer\.username\.errors'
        element :register_password_error, '#customer\.password\.errors'
        element :register_confirm_password_error, '#repeatedPassword\.errors'
        element :register_phone_error, '#customer\.phoneNumber\.errors'

        #Elementos da recuperaçao de senha
        element :forgot_first_name, '#firstName'
        element :forgot_last_name, '#lastName'
        element :forgot_address, '#address\.street'
        element :forgot_city, '#address\.city'
        element :forgot_state, '#address\.state'
        element :forgot_zip_code, '#address\.zipCode'
        element :forgot_ssn, '#ssn'
        element :forgot_form_button, 'input[value="Find My Login Info"]'
        element :forgot_success, '#rightPanel>h1'
        element :forgot_first_name_error, '#firstName\.errors'
        element :forgot_last_name_error, '#lastName\.errors'
        element :forgot_address_error, '#address\.street\.errors'
        element :forgot_city_error, '#address\.city\.errors'
        element :forgot_state_error, '#address\.state\.errors'
        element :forgot_zip_code_error, '#address\.zipCode\.errors'
        element :forgot_ssn_error, '#ssn\.errors'
    end
end
